version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    networks:
      - backend

  postgres:
    image: postgres
    restart: always
    ports:
      - '5044:5432'
    environment:
      POSTGRES_USER: hello
      POSTGRES_PASSWORD: local
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - backend

networks:
  backend:
    driver: bridge
